In this file, I will build the first model for corpus.

In [20]:
import os
cdir = os.path.abspath(os.path.dirname("__file__"))

import sys
sys.path.insert(0, cdir + "/..")

In [84]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import cross_val_score
import pandas as pd
import numpy as np
from modules.word_process import *
from sklearn.feature_extraction.text import TfidfVectorizer

Load pickle data

In [31]:
X_train = np.load('../data/processed/X_train.pkl')
tfidf_words_train = np.load('../data/processed/tfidf_words_train.pkl')
y_train = np.load('../data/processed/y_train.pkl')
X_test = np.load('../data/processed/X_test.pkl')
y_test = np.load('../data/processed/y_test.pkl')
tfidf =np.load('../data/processed/tfidf.pkl')

In [32]:
tfidf_words_train.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [33]:
test = word_processor(X_test,0)

In [34]:
test_words = test.process('porter')

In [36]:
tfidf_words_test = tfidf.transform(test_words)

In [50]:
mnb = MultinomialNB()
scores = cross_val_score(mnb, tfidf_words_train.toarray(),y_train, cv =5,n_jobs=-1,scoring="accuracy")
np.mean(scores)

0.97957808083247921

In [52]:
mnb.fit(tfidf_words_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [46]:
from sklearn.metrics import accuracy_score

In [54]:
accuracy_score(y_test,mnb.predict(xtest))

0.97615606936416188

In [53]:
mnb.predict(xtest)

array([1, 0, 1, ..., 0, 1, 1])

In [139]:
string = np.array([["I am awesome"]])
string = word_processor(string,0)

In [140]:
a = string.process('porter')

In [141]:
mnb.predict(tfidf.transform(a).toarray())

array([1])